const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

const sandbox = { window: {} };
vm.runInNewContext(fs.readFileSync(path.join(__dirname, "core.js"), "utf8"), sandbox);
const generate = sandbox.window.StraightCut.generate;

const test = (name, fn) => {
  fn();
  console.log("PASS", name);
};

// A minimal G0/G1 follower, absolute mode only (this plugin never emits G91) -
// enough to check the file states every axis it moves through.
function follow(text) {
  let x = 0, y = 0, z = 0;
  const seen = { x: false, y: false, z: false };
  const positions = [];
  for (const line of text.split("\n")) {
    const g = line.match(/^G[01]\b/);
    if (!g) continue;
    for (const [axis, set] of [["X", (v) => (x = v)], ["Y", (v) => (y = v)], ["Z", (v) => (z = v)]]) {
      const m = line.match(new RegExp(axis + "(-?[0-9.]+)"));
      if (m) {
        set(parseFloat(m[1]));
        seen[axis.toLowerCase()] = true;
      }
    }
    positions.push({ x, y, z, sawX: seen.x, sawY: seen.y, sawZ: seen.z });
  }
  return positions;
}

const BASE = { direction: "X+", distance: 254, cutSpeed: 2300, safeHeight: 25, pierceHeight: 3, cutHeight: 1.5, pierceDelay: 3 };

test("every motion line's position is on record - no axis is ever implicit", () => {
  for (const opts of [
    BASE,
    { ...BASE, direction: "Y-", thc: true },
    { ...BASE, direction: "X-", units: "inch" },
    { ...BASE, direction: "Y+", probeCode: "G38.2 Z-10 F50\nG92 Z0" },
  ]) {
    const positions = follow(generate(opts));
    assert.ok(positions.length > 0);
    for (const p of positions) {
      assert.ok(p.sawX && p.sawY && p.sawZ, `every axis should have a stated value by ${JSON.stringify(p)}`);
    }
  }
});

test("the first move states X0 Y0 explicitly, so nothing but the very first (undefined-origin) segment is lost", () => {
  const lines = generate(BASE).split("\n");
  const firstMotion = lines.find((l) => /^G0\b/.test(l));
  assert.equal(firstMotion, "G0 X0 Y0 Z25");
});

test("the cut line itself still carries only the axis being cut - no unwanted Y/X word on it", () => {
  const xCut = generate(BASE).split("\n").find((l) => l.startsWith("G1 "));
  assert.equal(xCut, "G1 X254 F2300");
  const yCut = generate({ ...BASE, direction: "Y-" }).split("\n").find((l) => l.startsWith("G1 "));
  assert.equal(yCut, "G1 Y-254 F2300");
});

test("matches the exact sequence a THC-enabled X+ cut previously produced, plus the X0 Y0 fix", () => {
  const expected = [
    "; Straight Cut generated by UGS Dashboard",
    "; Direction X+ · Distance 254 mm",
    "G90",
    "G21",
    "G0 X0 Y0 Z25",
    "G0 Z3",
    "M3",
    "G4 P3",
    "G0 Z1.5",
    "M8",
    "G1 X254 F2300",
    "M5",
    "G4 P0.5",
    "M9",
    "G0 Z25",
    "",
  ].join("\n");
  assert.equal(generate({ ...BASE, thc: true }), expected);
});
