(function (root) {
  'use strict';

  function finite(value, label) {
    const number = Number(value);
    if (!Number.isFinite(number)) throw new Error(label + ' must be a number.');
    return number;
  }

  function positive(value, label) {
    const number = finite(value, label);
    if (number <= 0) throw new Error(label + ' must be greater than zero.');
    return number;
  }

  function nonNegative(value, label) {
    const number = finite(value, label);
    if (number < 0) throw new Error(label + ' cannot be negative.');
    return number;
  }

  function format(value) {
    return Number(value).toFixed(6).replace(/\.0+$/, '').replace(/(\.\d*?)0+$/, '$1');
  }

  function generate(options) {
    const direction = String(options.direction || '').toUpperCase();
    const directionMatch = /^([XY])([+-])$/.exec(direction);
    if (!directionMatch) throw new Error('Choose a cut direction.');

    const axis = directionMatch[1];
    const sign = directionMatch[2] === '-' ? '-' : '';
    const distance = positive(options.distance, 'Distance');
    const speed = positive(options.cutSpeed, 'Cut speed');
    const safeHeight = finite(options.safeHeight, 'Safe move height');
    const pierceHeight = finite(options.pierceHeight, 'Pierce height');
    const cutHeight = finite(options.cutHeight, 'Cut height');
    const pierceDelay = nonNegative(options.pierceDelay, 'Pierce delay');
    const units = options.units === 'inch' ? 'G20' : 'G21';
    const probe = String(options.probeCode || '').replace(/\r\n?/g, '\n').trim();
    const thc = Boolean(options.thc);

    const lines = [
      '; Straight Cut generated by UGS Dashboard',
      `; Direction ${direction} · Distance ${format(distance)} ${options.units === 'inch' ? 'in' : 'mm'}`,
      'G90',
      units,
      // X0 Y0 on this first move states outright what every other line already
      // assumes - the cut starts at the active work origin - since the file never
      // otherwise mentions the axis that isn't being cut (Y for an X cut, X for a
      // Y cut). Without an explicit word for it, UGS's own position tracking (and
      // so the Dashboard visualizer) has no numeric value for that axis anywhere
      // in the file and drops every segment as a result - nothing rendered, even
      // though the file ran on the machine exactly as documented. This changes
      // nothing about where the machine actually goes for the documented
      // "starts from the active work origin" use - it only writes out the
      // starting position the file already relies on.
      `G0 X0 Y0 Z${format(safeHeight)}`,
    ];

    if (probe) lines.push('; Custom probe code', ...probe.split('\n'));

    lines.push(
      `G0 Z${format(pierceHeight)}`,
      'M3',
      `G4 P${format(pierceDelay)}`,
      `G0 Z${format(cutHeight)}`,
    );

    if (thc) lines.push('M8');

    lines.push(`G1 ${axis}${sign}${format(distance)} F${format(speed)}`, 'M5');

    if (thc) lines.push('G4 P0.5', 'M9');

    lines.push(`G0 Z${format(safeHeight)}`);
    return lines.join('\n') + '\n';
  }

  root.StraightCut = { generate };
})(window);
